# Generated by Django 2.0.2 on 2019-11-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentNumber', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.TextField()),
                ('Address', models.TextField()),
                ('PhoneNumber', models.IntegerField()),
                ('Class', models.IntegerField()),
            ],
        ),
    ]
