# Generated by Django 2.0.2 on 2019-12-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_data_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='PhoneNumber',
            field=models.TextField(),
        ),
    ]
