# Generated by Django 2.0.2 on 2019-12-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_auto_20191201_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Gender',
            field=models.TextField(),
        ),
    ]
